const entries = [
    {"label":"Playlist Before 2022","url":"https://www.youtube.com/embed/videoseries?list=PLymm91FIIzMsAti8VaoMFLvdJSQa_tYoF","sourceName":"youtubeLogo"},
    {"label":"🇹🇭 - 🇦🇷 Full Highlights | VNL2018","url":"https://www.youtube.com/embed/M6BXAlPJwM8","sourceName":"Sports Time"},
    {"label":"🇹🇭 vs 🇯🇵 วอลเลย์บอลหญิงเนชั่นลีกส์ 2018 ตบยื้อ5Set!! ดิวส์มาราธอน 22-20แต้ม","url":"https://www.youtube.com/embed/W-3wEr_emP4","sourceName":"สนุกวอลเลย์บอล"},
    {"label":"🇹🇭 vs 🇵🇱 — VNL2018","url":"https://www.youtube.com/embed/TFYqfifFmCk","sourceName":"Sports Time"},
    {"label":"🇰🇷 vs. 🇹🇭 | Olympic Qualifier 2016","url":"https://www.youtube.com/embed/DpP9qNc5Qks","sourceName":"Volleyball World"},
    {"label":"🇯🇵 vs. 🇹🇭 - Full Match | World Grand Prix 2017","url":"https://www.youtube.com/embed/IwBXuOI0U1o","sourceName":"Volleyball World"},
    {"label":"🇹🇭 🆚 🇷🇺 - Full Match | World Championships 2018","url":"https://www.youtube.com/embed/cuF1G5-ur1c","sourceName":"Volleyball World"},
    {"label":"🇺🇸 vs. 🇹🇭 - Full Match | World Championship 2018","url":"https://www.youtube.com/embed/7vtytDEt04A","sourceName":"Volleyball World"},
    {"label":"🇹🇭 vs 🇷🇺 | World Championship 2018","url":"https://www.youtube.com/embed/eCxNoF-GWjA","sourceName":"Thailand Volleyball"},
    {"label":"🇹🇭 🆚 🇰🇷 - Full Match | World Championships 2018","url":"https://www.youtube.com/embed/wCFh3ScLyFo","sourceName":"Volleyball World"},
    {"label":"Playlist VNL2022","url":"https://www.youtube.com/embed/videoseries?list=PLymm91FIIzMuzRT6QX9S4yurWYtiKr0wk","sourceName":"youtubeLogo"},
    {"label":"🇹🇭 Has Made One of the Most Legendary Victories in VNL 2022 !!!","url":"https://www.youtube.com/embed/94Z5fk4ucc0","sourceName":"Power Volleyball"},
    {"label":"🇹🇭 vs. 🇨🇳 - Highlights Week 1 | VNL 2022","url":"https://www.youtube.com/embed/XE46XPAwSAI","sourceName":"Volleyball World"},
    {"label":"🇹🇭 vs. 🇧🇪 - Highlights Week 1 | VNL 2022","url":"https://www.youtube.com/embed/RE1TOkZ8TuQ","sourceName":"Volleyball World"},
    {"label":"🇹🇭 vs. 🇧🇬 - Highlights Week 1 | VNL 2022","url":"https://www.youtube.com/embed/92EvAZIiThI","sourceName":"Volleyball World"},
    {"label":"🇹🇭 vs. 🇷🇸 - Highlights Week 1 | VNL 2022","url":"https://www.youtube.com/embed/wHuxT6egOT8","sourceName":"Volleyball World"},
    {"label":"🇵🇱 vs. 🇹🇭 - Highlights Week 2 | VNL 2022","url":"https://www.youtube.com/embed/gdgBSKlmLYo","sourceName":"Volleyball World"},
    {"label":"🇹🇭 vs. 🇺🇸 - Highlights Week 2 | VNL 2022","url":"https://www.youtube.com/embed/LRZLQZYq9Ow","sourceName":"Volleyball World"},
    {"label":"🇨🇦 vs. 🇹🇭 - Highlights Week 2 | VNL 2022","url":"https://www.youtube.com/embed/jfbQDR1tMXM","sourceName":"Volleyball World"},
    {"label":"🇧🇷 vs. 🇹🇭 - Highlights Week 3 | VNL 2022","url":"https://www.youtube.com/embed/fycJYnCtUmE","sourceName":"Volleyball World"},
    {"label":"Thailand Volleyball Team Destroyed Korea in VNL 2022","url":"https://www.youtube.com/embed/FeC09MzV7_o","sourceName":"Power Volleyball"},
    {"label":"🇹🇭 vs. 🇩🇴 - Highlights Week 3 | VNL 2022","url":"https://www.youtube.com/embed/Q09VwYoaJCg","sourceName":"Volleyball World"},
    {"label":"🇯🇵 vs. 🇹🇭 - Highlights Week 2 | VNL 2022","url":"https://www.youtube.com/embed/4ZxkdZqRFD0","sourceName":"Volleyball World"},
    {"label":"🇹🇭 vs. 🇰🇷 - Highlights Week 3 | VNL 2022","url":"https://www.youtube.com/embed/jlMRtJTN-4A","sourceName":"Volleyball World"},
    {"label":"🇹🇷 vs. 🇹🇭 - Highlights Quarter Finals | VNL 2022","url":"https://www.youtube.com/embed/JVk0kJf3YJY","sourceName":"Volleyball World"},
    {"label":"🇧🇷 vs.  🇹🇭 - Full Match | VNL 2022","url":"https://www.youtube.com/embed/Iy8HmOAQQVs","sourceName":"Volleyball World"},
    {"label":"🇹🇷 vs. 🇹🇭 - Full Match | VNL 2022","url":"https://www.youtube.com/embed/oqTs2sZ-fN0","sourceName":"Volleyball World"},  
    {"label":"Thailand Has Made One of the Greatest Victories in VNL 2022","url":"https://www.youtube.com/embed/MhV1TbHrqC8","sourceName":"Power Volleyball"},
    {"label":"Thailand & Belgium Played the Most Dramatic Match in VNL 2022","url":"https://www.youtube.com/embed/3pRrze0zui0","sourceName":"Power Volleyball"},
    {"label":"Thailand Has Made One of the Greatest Victories in Women's Volleyball History !!!","url":"https://www.youtube.com/embed/MXc5tQ88mk0","sourceName":"Power Volleyball"},
    {"label":"LEGENDARY MATCH | THAILAND vs CHINA | VNL 2022","url":"https://www.youtube.com/embed/uf2nnP0CmZQ","sourceName":"Power Volleyball"},
    {"label":"Playlist WC2022","url":"https://www.youtube.com/embed/videoseries?list=PLymm91FIIzMvW9bybnie0YeUNfjjKoNdX","sourceName":"youtubeLogo"},
    {"label":"🇹🇭 vs. 🇺🇸 - Full Match | World Championship 2022","url":"https://www.youtube.com/embed/ymO5tIxUqAg","sourceName":"Volleyball World"},
    {"label":"🇹🇭 THA vs. 🇭🇷 CRO - Highlights  Phase 1 | World Championship 2022","url":"https://www.youtube.com/embed/wkO-MdwRieY","sourceName":"Volleyball World"},
    {"label":"🇩🇴 vs. 🇹🇭 - Highlights  Phase 1| World Championship 2022","url":"https://www.youtube.com/embed/Hf1BEaenOCc","sourceName":"Volleyball World"},
    {"label":"Thailand Volleyball Team Destroyed Korea in World Championship 2022","url":"https://www.youtube.com/embed/4R6kwZ96qRM","sourceName":"Power Volleyball"},
    {"label":"HISTORICAL MATCH | THAILAND vs TURKIYE | World Championship 2022","url":"https://www.youtube.com/embed/PCx9ca6ZN5M","sourceName":"Power Volleyball"},
    {"label":"🇺🇸 vs. 🇹🇭 - Highlights  Phase 2| World Championship 2022","url":"https://www.youtube.com/embed/5eFgL1iCF4U","sourceName":"Volleyball World"},
    {"label":"🇹🇷 TÜR vs. 🇹🇭 THA - Highlights Phase 1 | World Championship 2022","url":"https://www.youtube.com/embed/cLOb_GS_nJ0","sourceName":"Volleyball World"},
    {"label":"The Most Dramatic Match in Thailand Volleyball History !!!","url":"https://www.youtube.com/embed/ugtM1xxCXzs","sourceName":"Power Volleyball"},
    {"label":"Playlist 2023","url":"https://www.youtube.com/embed/videoseries?list=PLymm91FIIzMv0FwGynzaAmUx0aauB2hXr","sourceName":"youtubeLogo"},
    {"label":"🇮🇹 vs. 🇹🇭 - Highlights Week 1 | VNL 2023","url":"https://www.youtube.com/embed/g_8_h-Fpfeo","sourceName":"Volleyball World"},
    {"label":"🇨🇦 vs. 🇹🇭 - Highlights Week 1 | VNL 2023","url":"https://www.youtube.com/embed/X83GsHhs1zo","sourceName":"Volleyball World"},
    {"label":"🇹🇭 vs. 🇰🇷 - Highlights Week 1 | VNL 2023","url":"https://www.youtube.com/embed/GvhdVW1PJCU","sourceName":"Volleyball World"},
    {"label":"🇷🇸 vs. 🇹🇭 - Highlights Week 2 | VNL 2023","url":"https://www.youtube.com/embed/GjGjNaeebeE","sourceName":"Volleyball World"},
    {"label":"AVC 2023 | 🇹🇭 vs 🇯🇵 |  5 ก.ย. 66","url":"https://www.youtube.com/embed/BveD70tcbvw","sourceName":"PPTV HD 36"},
    {"label":"NEVER Underestimate Volleyball Team Thailand - HERE'S WHY !!!","url":"https://www.youtube.com/embed/MDZFt2HJL4M","sourceName":"Power Volleyball"},
    {"label":"This is the Most Dramatic Victory in Thailand Volleyball History","url":"https://www.youtube.com/embed/kwFmHYiWI-k","sourceName":"Power Volleyball"},
    {"label":"🇹🇭 vs 🇸🇮 | OQT 2023","url":"https://www.youtube.com/embed/uDpZBdHpKm4","sourceName":"Power Volleyball"},
    {"label":"🇹🇭 vs 🇰🇷 | OQT 2023","url":"https://www.youtube.com/embed/dMAaq-DXW_k","sourceName":"Power Volleyball"},
    {"label":"🇹🇭 vs 🇨🇴 | OQT 2023","url":"https://www.youtube.com/embed/ead1CmyRPGM","sourceName":"Power Volleyball"},
    {"label":"Playlist 2024","url":"https://www.youtube.com/embed/videoseries?list=PLymm91FIIzMtMv3yy56O0SQNmgWvG96YX","sourceName":"youtubeLogo"},
    {"label":"🇹🇭 vs. 🇧🇷 - Quarter Finals | VNL 2024","url":"https://www.youtube.com/embed/fPUJfwYIBQc","sourceName":"Volleyball World"},
    {"label":"🇧🇬 vs. 🇹🇭 - Highlights | Week 3 | VNL 2024","url":"https://www.youtube.com/embed/RCdADH7jK-8","sourceName":"Volleyball World"},
    {"label":"4th SEA V.League THA vs VIE Korat","url":"https://www.youtube.com/embed/uigAjoUYFfc","sourceName":"One"},
    {"label":"KOVO V-league","url":"https://www.youtube.com/embed/videoseries?list=PLymm91FIIzMuxfxS6DoRsX8LyVG3Nmku8","sourceName":"kovo"}
];

const buttomImg = {'Sports Time':'https://i.ibb.co/mFPhThL/ch3-profile.jpg',
    "youtubeLogo":"https://i.ibb.co/QFr3tn1/ballv2-192x192.png",
    'สนุกวอลเลย์บอล':'https://i.ibb.co/mFPhThL/ch3-profile.jpg',
    'Volleyball World':'https://i.ibb.co/k5nkPDs/VBW-favicon-32x32.png',
    'Thailand Volleyball':'https://i.ibb.co/jH7GDWx/workpoint-profile.jpg',
    'Power Volleyball':'https://i.ibb.co/Ntcc2bK/PWV-favicon-32x32.png',
    'PPTV HD 36':'https://i.ibb.co/qmJ6Zyy/pptv-profile.jpg',
    "kovo":"https://i.ibb.co/k9bC8Fp/Pornpun.jpg",
    "One":"https://i.ibb.co/MctFZx3/images-q-tbn-ANd9-Gc-TUq-BDB6d-YHIw1-CV6hd-MQa1w-HYTw-W4nenx-HDQ-s.jpg"};
